# Generated by Django 6.0.1 on 2026-03-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
