# Generated by Django 6.0.1 on 2026-03-02 12:34

import django.db.models.deletion
import learningPlatform.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChapterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('markdown', 'Markdown'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], db_index=True, max_length=20)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='protected/quiz/questions/')),
                ('markdown', models.TextField(blank=True)),
                ('rendered_html', models.TextField(blank=True, editable=False)),
                ('question_type', models.CharField(choices=[('mcq', 'Single Choice'), ('msq', 'Multiple Choice'), ('numeric', 'Numeric')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('marks', models.FloatField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_preview', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='course.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarkdownContent',
            fields=[
                ('chaptercontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.chaptercontent')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('markdown_content', models.TextField()),
                ('rendered_html', models.TextField(blank=True, editable=False)),
            ],
            bases=('course.chaptercontent',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('chaptercontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.chaptercontent')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
            ],
            bases=('course.chaptercontent',),
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('chaptercontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.chaptercontent')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(storage=learningPlatform.storage.PrivateMediaStorage(), upload_to='chapter_videos/')),
            ],
            bases=('course.chaptercontent',),
        ),
        migrations.AddField(
            model_name='chaptercontent',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='course.chapter'),
        ),
        migrations.CreateModel(
            name='NumericAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_answer', to='course.question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='course.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='course_thumbnails/')),
                ('demo_video_url', models.FileField(upload_to='course_demo_videos/')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='course.category')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.PROTECT, related_name='courses_as_mentor', to=settings.AUTH_USER_MODEL)),
                ('mentors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'mentor'}, related_name='mentored_courses', to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(blank=True, related_name='course', to='course.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_preview', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='course.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.unit'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course.quiz'),
        ),
        migrations.AddIndex(
            model_name='chaptercontent',
            index=models.Index(fields=['chapter', 'order'], name='course_chap_chapter_55f9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='chaptercontent',
            index=models.Index(fields=['chapter', 'content_type'], name='course_chap_chapter_173ef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chaptercontent',
            unique_together={('chapter', 'order')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='course_cour_slug_235a66_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='course_cour_status_57ffd9_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['course', 'order'], name='course_unit_course__df761f_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['course', 'slug'], name='course_unit_course__c375f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_unit_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='unique_unit_slug_per_course'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['unit', 'order'], name='course_chap_unit_id_7ddcec_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['unit', 'slug'], name='course_chap_unit_id_4895bd_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_published'], name='course_chap_is_publ_1d4661_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('unit', 'order'), ('unit', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'order')},
        ),
    ]
