# Generated by Django 6.0.1 on 2026-03-21 11:39

import course.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='demo_video_url',
            field=models.FileField(blank=True, null=True, upload_to='course_demo_videos/', validators=[course.models.course.validate_video]),
        ),
    ]
