# Generated by Django 6.0.1 on 2026-03-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_demo_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='demo_video_url',
            new_name='demo_video',
        ),
    ]
