# Generated by Django 6.0.1 on 2026-03-21 12:05

import course.models.course
import learningPlatform.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_demo_video_url_course_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='public/course_demo_videos/', validators=[course.models.course.validate_video]),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='public/course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(storage=learningPlatform.storage.PrivateMediaStorage(), upload_to='protected/chapter_videos/'),
        ),
    ]
