# Generated by Django 6.0.1 on 2026-03-22 18:47

import course.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_demo_video_alter_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='public/course_demo_videos/', validators=[course.models.course.validate_video]),
        ),
    ]
