# Generated by Django 6.0.1 on 2026-03-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_demo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_preview',
        ),
    ]
