# Generated by Django 6.0.1 on 2026-03-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_unit_is_preview'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chapter',
            name='course_chap_is_publ_1d4661_idx',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='is_published',
        ),
    ]
