# Generated by Django 6.0.1 on 2026-03-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_chapter_course_chap_is_publ_1d4661_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('unit', 'slug')},
        ),
    ]
