services:
  db:
    image: postgres:16
    container_name: learning-db
    restart: always
    environment:
      POSTGRES_USER: mohit
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: learning_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    container_name: learning-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: learning-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  tusd:
    image: tusproject/tusd:latest
    container_name: learning-tusd
    restart: always
    ports:
      - "1080:8080"
    volumes:
      - "../media:/data"
    environment:
      TUSD_HOOKS_HTTP_HEADER_X_HOOK_SECRET: "9bUVNyVG5QR0s11t4NwL9O32yaI8nY"
    command:
      - "-upload-dir=/data"
      - "-base-path=/tus/"
      - "-hooks-http=http://host.docker.internal:8000/tus/hooks/"
      - "-hooks-http-forward-headers=Authorization,X-User-ID,X-Request-ID,Cookie"
      - "-hooks-enabled-events=pre-create,post-finish"
      - "-cors-allow-origin=http://localhost:8000"
      - "-cors-allow-credentials"
      - "-cors-allow-headers=Authorization,X-User-ID,X-Request-ID,Cookie"

volumes:
  postgres_data:
  pgadmin_data:
